"""Initial migration

Revision ID: 1de4365ff5a7
Revises: 92bf6d1ff3fa
Create Date: 2025-04-03 14:51:20.080700

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1de4365ff5a7'
down_revision = '92bf6d1ff3fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.alter_column('count',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.Integer(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.alter_column('count',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=500),
               nullable=False)

    # ### end Alembic commands ###
