"""Initial migration

Revision ID: 28e97945762a
Revises: e8ca2a77bb4e
Create Date: 2025-03-27 17:17:37.378589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28e97945762a'
down_revision = 'e8ca2a77bb4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('module_branches', schema=None) as batch_op:
        batch_op.drop_constraint('module_branches_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('module_branches_ibfk_1', type_='foreignkey')

    with op.batch_alter_table('product_modules', schema=None) as batch_op:
        batch_op.drop_constraint('product_modules_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('product_modules_ibfk_2', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_modules', schema=None) as batch_op:
        batch_op.create_foreign_key('product_modules_ibfk_2', 'products', ['product_id'], ['id'])
        batch_op.create_foreign_key('product_modules_ibfk_1', 'modules', ['module_id'], ['id'])

    with op.batch_alter_table('module_branches', schema=None) as batch_op:
        batch_op.create_foreign_key('module_branches_ibfk_1', 'branches', ['branch_id'], ['id'])
        batch_op.create_foreign_key('module_branches_ibfk_2', 'modules', ['module_id'], ['id'])

    # ### end Alembic commands ###
