"""Initial migration

Revision ID: 45438ca9e5c2
Revises: a257fb8341b9
Create Date: 2025-03-27 17:01:30.142417

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '45438ca9e5c2'
down_revision = 'a257fb8341b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('logs')
    with op.batch_alter_table('modules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('branch', sa.String(length=255), nullable=True))
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('modules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', mysql.VARCHAR(length=1000), nullable=True))
        batch_op.drop_column('branch')

    op.create_table('logs',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('module_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('log_file_path', mysql.VARCHAR(length=500), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
