"""Initial migration

Revision ID: 92bf6d1ff3fa
Revises: c7e5ae7e2729
Create Date: 2025-04-02 18:42:20.598493

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '92bf6d1ff3fa'
down_revision = 'c7e5ae7e2729'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('log_name', sa.String(length=255), nullable=False))
        batch_op.drop_column('module_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('module_name', mysql.VARCHAR(length=255), nullable=False))
        batch_op.drop_column('log_name')

    # ### end Alembic commands ###
