"""Initial migration

Revision ID: d9ef1246f3f7
Revises: 28e97945762a
Create Date: 2025-03-27 18:04:35.563708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9ef1246f3f7'
down_revision = '28e97945762a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('branches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tag_version', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('branches', schema=None) as batch_op:
        batch_op.drop_column('tag_version')

    # ### end Alembic commands ###
